Feature: support SLB to expose raven service
openyurtio/raven-controller-manager pull request #35
Opened 2023-02-16 01:39 UTC by njucjc

2023-02-16 01:55 UTC, rambohe-ch commented
@njucjc maybe as you known, controllers in this repo(raven-controller-manager) is under moving into `yurt-manager` component in `openyurtio/openyurt` repo. so how about post this pull request into `yurt-manager` component?

2023-02-17 02:09 UTC, BSWANG requested changes

2023-02-17 02:09 UTC, BSWANG commented on pkg/ravencontroller/apis/raven/v1alpha1/gateway_types.go
> +	Type ExposeType `json:"type,omitempty"`
名字叫ExposeType是否会好一些，要不然生成的CRD的字段容易产生歧义

2023-02-17 03:43 UTC, njucjc commented on pkg/ravencontroller/apis/raven/v1alpha1/gateway_types.go
> +	Type ExposeType `json:"type,omitempty"`
done

2023-02-17 08:12 UTC, njucjc commented
> I suggest that we can merge this PR first, and then moving it into `yurt-manager` together.

2023-02-17 08:24 UTC, rambohe-ch commented
> > @rambohe-ch I suggest that we can merge this PR first, and then moving it into `yurt-manager` together.

@njucjc ok, i have no problem. and would you be able to migrate this controller into yurt-manager?

2023-02-20 02:02 UTC, merged